# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventana_config(object):
    def setupUi(self, ventana_config):
        ventana_config.setObjectName("ventana_config")
        ventana_config.resize(462, 753)
        ventana_config.setStyleSheet("QWidget{\n"
"    background-color: #2C2C2C;\n"
"}\n"
"QLineEdit{\n"
"  background-color: #E3E3E3;\n"
"  border-radius: 4px;\n"
"  border: none;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"  border-bottom: 2px solid #D3D3D3;\n"
"  border-radius: 4px 4px 2px 2px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:white;\n"
"    letter-spacing: .5px;\n"
"}\n"
"QPushButton{\n"
" padding: 10px 25px;\n"
" background-color: #4CC713;\n"
" color: white;\n"
" text-decoration: none;\n"
" text-align: center;\n"
" border: none;\n"
" letter-spacing: .5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: #45a21a;\n"
" color: white;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ventana_config)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_des = QtWidgets.QLabel(parent=ventana_config)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_des.setFont(font)
        self.label_des.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_des.setObjectName("label_des")
        self.gridLayout.addWidget(self.label_des, 1, 1, 1, 1)
        self.label_gan = QtWidgets.QLabel(parent=ventana_config)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_gan.setFont(font)
        self.label_gan.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_gan.setObjectName("label_gan")
        self.gridLayout.addWidget(self.label_gan, 1, 0, 1, 1)
        self.label_prov = QtWidgets.QLabel(parent=ventana_config)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_prov.setFont(font)
        self.label_prov.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_prov.setObjectName("label_prov")
        self.gridLayout.addWidget(self.label_prov, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_anadir = QtWidgets.QPushButton(parent=ventana_config)
        self.pushButton_anadir.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons_svg/add_circle_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_anadir.setIcon(icon)
        self.pushButton_anadir.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_anadir.setObjectName("pushButton_anadir")
        self.verticalLayout.addWidget(self.pushButton_anadir)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_cancelar = QtWidgets.QPushButton(parent=ventana_config)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_cancelar.setFont(font)
        self.pushButton_cancelar.setStyleSheet("QPushButton{background-color: #e74c3c;}\n"
"\n"
"QPushButton:hover{background-color: #CB4335;}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons_svg/close_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cancelar.setIcon(icon1)
        self.pushButton_cancelar.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.horizontalLayout.addWidget(self.pushButton_cancelar)
        self.pushButton_guardar = QtWidgets.QPushButton(parent=ventana_config)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_guardar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons_svg/download_done_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_guardar.setIcon(icon2)
        self.pushButton_guardar.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_guardar.setObjectName("pushButton_guardar")
        self.horizontalLayout.addWidget(self.pushButton_guardar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(ventana_config)
        QtCore.QMetaObject.connectSlotsByName(ventana_config)

    def retranslateUi(self, ventana_config):
        _translate = QtCore.QCoreApplication.translate
        ventana_config.setWindowTitle(_translate("ventana_config", "Proveedores"))
        self.label_des.setText(_translate("ventana_config", "Descuento"))
        self.label_gan.setText(_translate("ventana_config", "Ganancia"))
        self.label_prov.setText(_translate("ventana_config", "Proveedor"))
        self.pushButton_cancelar.setText(_translate("ventana_config", "Cancelar"))
        self.pushButton_guardar.setText(_translate("ventana_config", "Guardar"))
